%global pybasever 3.6
%global pylibdir %{_libdir}/python%{pybasever}

%global __os_install_post /usr/lib/rpm/brp-compress \
  %{!?__debug_package:/usr/lib/rpm/brp-strip %{__strip}} \
  /usr/lib/rpm/brp-strip-static-archive %{__strip} \
  /usr/lib/rpm/brp-strip-comment-note %{__strip} %{__objdump} \
  /usr/lib/rpm/brp-python-hardlink

Name:		python36
Version:	3.6.5
Release:	9%{?dist}
Summary:	Python programming language

Group:		Development/Languages
License:	Python
URL:		https://www.python.org/
Source0:	Python-3.6.5.tgz

# Patches
Patch251: 00251-change-user-install-location.patch

BuildRequires:  autoconf, bzip2-devel, findutils, glibc-devel, gmp-devel, libffi-devel, libGL-devel
BuildRequires:  libX11-devel, ncurses-devel, net-tools, openssl-devel, pkgconfig, readline-devel
BuildRequires:  sqlite-devel, tcl-devel, tix-devel, tk-devel, xz-devel, zlib-devel
Requires:       expat, pkgconfig, zlib

%package devel
Summary:    Libraries and header files needed for Python 3 development
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
This package contains libraries and header files used to build applications
with and native libraries for Python 3

%description
Python is an interpreted, interactive, object-oriented programming
language often compared to Tcl, Perl, Scheme or Java. Python includes
modules, classes, exceptions, very high level dynamic data types and
dynamic typing. Python supports interfaces to many system calls and
libraries, as well as to various windowing systems (X11, Motif, Tk,
Mac and MFC).

Programmers can write new built-in modules for Python in C or C++.
Python can be used as an extension language for applications that need
a programmable interface.

%prep
%setup -q -n Python-%{version}

%patch251 -p1

# remove this file, as it should be generated by the build
rm configure pyconfig.h.in

%build
autoconf
autoheader

%configure \
    --enable-ipv6 \
    --enable-shared \
    --with-computed-gotos=no \
    --with-dbmliborder=gdbm:ndbm:bdb \
    --with-system-expat \
    --with-system-ffi \
    --enable-loadable-sqlite-extensions \
    --without-ensurepip \
    --disable-optimizations

make %{?_smp_mflags}

%install
make DESTDIR=%{buildroot} INSTALL="install -p" install

mkdir -p $RPM_BUILD_ROOT/etc/profile.d
echo "export PYTHONPATH=$PYTHONPATH:/usr/lib64/python3.6:/usr/lib64/python3.6/lib-dynload" >> $RPM_BUILD_ROOT/etc/profile.d/python36.sh

%files devel
%{_bindir}/python3-config
%{_bindir}/python3.6-config
%{_bindir}/python3.6m-config
%{_libdir}/pkgconfig/python-3.6.pc
%{_libdir}/pkgconfig/python-3.6m.pc
%{_libdir}/pkgconfig/python3.pc
%{_includedir}/python3.6m/*.h

%files
%{_bindir}/python3
%{_bindir}/python3.6
%{_bindir}/python3.6m
%{_bindir}/pyvenv
%{_bindir}/pyvenv-3.6
%{_bindir}/2to3
%{_bindir}/2to3-3.6
%{_bindir}/idle3
%{_bindir}/idle3.6
%{_bindir}/pydoc3
%{_bindir}/pydoc3.6
%exclude /usr/lib/python%{pybasever}/cgi.py
%{_libdir}/*
%{_mandir}/*/*
/usr/lib/python%{pybasever}/*
/etc/profile.d/python36.sh

%changelog
* Wed May 16 2018 Andreas Muehlemann <andreas.muehlemann@switch.ch> - 3.6.5
- update to 3.6.5

* Wed Jan 17 2018 Andreas Muehlemann <andreas.muehlemann@switch.ch> - 3.6.4
- first version
